version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: videoforge_app
    expose:
      - "80"
    restart: always
    depends_on:
      - db
    volumes:
      - ./data/channels:/var/www/app/docker/data/channels  # Adicionando o volume

  db:
    image: mysql:8.0
    container_name: videoforge_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: videoforge_db
      MYSQL_USER: videoforge
      MYSQL_PASSWORD: videoforgepassword
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: videoforge_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: videoforge
      PMA_PASSWORD: videoforgepassword
    ports:
      - "1314:80"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: videoforge_nginx
    ports:
      - "1313:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  python:
    build:
      context: ..
      dockerfile: docker/Dockerfile-python
    container_name: videoforge_python
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
