version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: videoforge_app
    expose:
      - "1313"
    restart: always



  db:
    image: mysql:8.0
    container_name: videoforge_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: videoforge_db
      MYSQL_USER: videoforge
      MYSQL_PASSWORD: videoforgepassword
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: videoforge_nginx
    ports:
      - "80:80"  # Expondo a porta 80 para acesso externo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
