version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/etc/composer/Dockerfile
    container_name: videoforge_web
    ports:
      - "8080:80"
    volumes:
      - ../application:/usr/share/nginx/html
